### ISSUE TITLE
Facility for Global Configuration

### ISSUE THREAD

**Issue by illegalprime** [HackGT/buzzer#9]
Provide some way of inserting configuration or secrets (probably with a file for each).
So a conf file could be:
```yaml
port: 3000
production: true
plugins:
  slack:
    some_non_secret_conf: Hello
```

A secrets file is similar, but contains info we can't include in the public `biodomes` repo:
```yaml
plugins:
  twitter:
    api_key: 3243546787543546789
```

Also be able to override some / all of these options through environment variables.
